# Generated by Django 4.0.4 on 2022-06-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.IntegerField(choices=[(1, 'Włoska'), (2, 'Kebab'), (3, 'Sushi'), (4, 'Chińska'), (5, 'Burger')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Basen'), (2, 'Siłownia'), (3, 'Studio fitness'), (4, 'Kort')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.IntegerField(choices=[(1, 'Kino'), (2, 'Teatr'), (3, 'Restauracja'), (4, 'Pub'), (5, 'Sport')])),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_engine.food')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='search_engine.sport')),
            ],
        ),
    ]
