# Generated by Django 4.0.4 on 2022-06-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cuisine',
            field=models.IntegerField(choices=[(1, 'Włoska'), (2, 'Kebab'), (3, 'Sushi'), (4, 'Chińska'), (5, 'Burger')], null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Basen'), (2, 'Siłownia'), (3, 'Studio fitness'), (4, 'Kort')], null=True),
        ),
    ]
