# Generated by Django 4.0.4 on 2022-06-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='district',
            new_name='district_id',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='food',
            new_name='food_id',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='sport',
            new_name='sport_id',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='type',
            new_name='type_id',
        ),
    ]
