# Generated by Django 4.0.4 on 2022-06-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_rename_district_place_district_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='district_id',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='sport_id',
            new_name='sport',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='type_id',
            new_name='type',
        ),
    ]
